<?php

namespace App\Services;

use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\PhpWord;

class ReflectionDocxExportService
{
    public function export(array $results, string $url): array
    {
        // BEGIN FILE OUTPUT

    // add code for main folder generation

    $outputBasePath = storage_path('app/ddg-output');

    if (! is_dir($outputBasePath)) {
        mkdir($outputBasePath, 0755, true);
    }

    // generate the sub folders

    $sanitize = function ($value) {
        return str_replace(['/', '\\'], '-', $value);
    };

    $addFormattedParagraph = function ($section, $text) {
    $textRun = $section->addTextRun();

    $parts = preg_split('/(<i>.*?<\/i>)/is', $text, -1, PREG_SPLIT_DELIM_CAPTURE);

    foreach ($parts as $part) {
            if ($part === '') {
                continue;
            }

            if (preg_match('/^<i>(.*?)<\/i>$/is', $part, $m)) {
                $textRun->addText(strip_tags($m[1]), ['italic' => true]);
            } else {
                $textRun->addText(strip_tags($part));
            }
        }
    };

    $createdCount = 0;
    $skippedCount = 0;

    $createdFiles = [];
    $skippedFiles = [];

    foreach ($results as $entry) {
        $folderPath = $outputBasePath
        . DIRECTORY_SEPARATOR . $sanitize($entry['category'])
        . DIRECTORY_SEPARATOR . $sanitize($entry['range_folder'])
        . DIRECTORY_SEPARATOR . $sanitize($entry['chapter_folder']);

        if (! is_dir($folderPath)) {
            mkdir($folderPath, 0755, true);
        }

        // generate the wod /**
        
        $phpWord = new PhpWord();
        $section = $phpWord->addSection();

        // Title (scripture reference)
        $section->addText(
            $entry['scripture_reference'],
            ['bold' => true, 'size' => 14]
        );

        // Date line
        $section->addText('Posted at Daily Reflections on ' . $entry['day'] . ', ' . $entry['year']);

        // Word count
        $section->addText('Word Count: ' . $entry['word_count_formatted']);

        // Body

        $paragraphs = preg_split("/\n\s*\n/", $entry['content']);

        foreach ($paragraphs as $p) {
            $addFormattedParagraph($section, $p);
        }

        // Add spacing
        $section->addTextBreak(1);

        // Append footer: source URL + generated date

        // Source URL
        $section->addLink(
            $url,
            $url,
            ['italic' => true, 'size' => 10, 'color' => '0000FF']
        );

        // Generated line
        $section->addText(
            'File generated by the REFLECTIONS ARCHIVE BUILDER on ' . now()->format('F j, Y') . '.',
            ['size' => 10, 'color' => '666666']
        );

        $filePath = $folderPath
        . DIRECTORY_SEPARATOR
        . $entry['filename'] . '.docx';

        // Skip if file already exists and add to counter
if (file_exists($filePath)) {
    $skippedCount++;

    $skippedFiles[] = [
        'title' => $entry['scripture_reference'],
        'filename' => $entry['filename'] . '.docx',
        'path' => $filePath,
        'reason' => 'already exists',
    ];

        continue;
    }

    // Save file
    $writer = IOFactory::createWriter($phpWord, 'Word2007');
    $writer->save($filePath);
    $createdCount++;

    $createdFiles[] = [
        'title' => $entry['scripture_reference'],
        'filename' => $entry['filename'] . '.docx',
        'path' => $filePath,
    ];

    
    }

    return [
        'results' => $results,
        'url' => $url,
        'createdCount' => $createdCount,
        'skippedCount' => $skippedCount,
        'createdFiles' => $createdFiles,
        'skippedFiles' => $skippedFiles,
    ];
    }
}