<?php

return [

    'chapter_counts' => [
        'Matthew' => 28,
        'Mark' => 16,
        'Luke' => 24,
        'John' => 21,
        'Acts' => 28,
        'Romans' => 16,
        '1 Corinthians' => 16,
        '2 Corinthians' => 13,
        'Galatians' => 6,
        'Ephesians' => 6,
        'Philippians' => 4,
        'Colossians' => 4,
        '1 Thessalonians' => 5,
        '2 Thessalonians' => 3,
        '1 Timothy' => 6,
        '2 Timothy' => 4,
        'Titus' => 3,
        'Philemon' => 1,
        'Hebrews' => 13,
        'James' => 5,
        '1 Peter' => 5,
        '2 Peter' => 3,
        '1 John' => 5,
        '2 John' => 1,
        '3 John' => 1,
        'Jude' => 1,
        'Revelation' => 22,

        // Add OT as needed later
        '2 Chronicles' => 36,
        'Psalms' => 150,
        'Psalm' => 150,
        'Song of Solomon' => 8,
        'The Song of Solomon' => 8,
        'Exodus' => 40,

    ],

    'category_map' => [
        
        // Gospels
        'Matthew' => 'Gospels',
        'Mark' => 'Gospels',
        'Luke' => 'Gospels',
        'John' => 'Gospels',

        // Psalms
        'Psalm' => 'Psalms',
        'Psalms' => 'Psalms',

        // New Testament w/o Gospels
        'Acts' => 'New Testament w/o Gospels',
        'Romans' => 'New Testament w/o Gospels',
        '1 Corinthians' => 'New Testament w/o Gospels',
        '2 Corinthians' => 'New Testament w/o Gospels',
        'Galatians' => 'New Testament w/o Gospels',
        'Ephesians' => 'New Testament w/o Gospels',
        'Philippians' => 'New Testament w/o Gospels',
        'Colossians' => 'New Testament w/o Gospels',
        '1 Thessalonians' => 'New Testament w/o Gospels',
        '2 Thessalonians' => 'New Testament w/o Gospels',
        '1 Timothy' => 'New Testament w/o Gospels',
        '2 Timothy' => 'New Testament w/o Gospels',
        'Titus' => 'New Testament w/o Gospels',
        'Philemon' => 'New Testament w/o Gospels',
        'Hebrews' => 'New Testament w/o Gospels',
        'James' => 'New Testament w/o Gospels',
        '1 Peter' => 'New Testament w/o Gospels',
        '2 Peter' => 'New Testament w/o Gospels',
        '1 John' => 'New Testament w/o Gospels',
        '2 John' => 'New Testament w/o Gospels',
        '3 John' => 'New Testament w/o Gospels',
        'Jude' => 'New Testament w/o Gospels',
        'Revelation' => 'New Testament w/o Gospels',

        // Old Testament w/o Psalms
        'Genesis' => 'Old Testament--w/o Psalms',
        'Exodus' => 'Old Testament--w/o Psalms',
        'Leviticus' => 'Old Testament--w/o Psalms',
        'Numbers' => 'Old Testament--w/o Psalms',
        'Deuteronomy' => 'Old Testament--w/o Psalms',
        'Joshua' => 'Old Testament--w/o Psalms',
        'Judges' => 'Old Testament--w/o Psalms',
        'Ruth' => 'Old Testament--w/o Psalms',
        '1 Samuel' => 'Old Testament--w/o Psalms',
        '2 Samuel' => 'Old Testament--w/o Psalms',
        '1 Kings' => 'Old Testament--w/o Psalms',
        '2 Kings' => 'Old Testament--w/o Psalms',
        '1 Chronicles' => 'Old Testament--w/o Psalms',
        '2 Chronicles' => 'Old Testament--w/o Psalms',
        'Ezra' => 'Old Testament--w/o Psalms',
        'Nehemiah' => 'Old Testament--w/o Psalms',
        'Esther' => 'Old Testament--w/o Psalms',
        'Job' => 'Old Testament--w/o Psalms',
        'Proverbs' => 'Old Testament--w/o Psalms',
        'Ecclesiastes' => 'Old Testament--w/o Psalms',
        'Song of Solomon' => 'Old Testament--w/o Psalms',
        'The Song of Solomon' => 'Old Testament--w/o Psalms',
        'Isaiah' => 'Old Testament--w/o Psalms',
        'Jeremiah' => 'Old Testament--w/o Psalms',
        'Lamentations' => 'Old Testament--w/o Psalms',
        'Ezekiel' => 'Old Testament--w/o Psalms',
        'Daniel' => 'Old Testament--w/o Psalms',
        'Hosea' => 'Old Testament--w/o Psalms',
        'Joel' => 'Old Testament--w/o Psalms',
        'Amos' => 'Old Testament--w/o Psalms',
        'Obadiah' => 'Old Testament--w/o Psalms',
        'Jonah' => 'Old Testament--w/o Psalms',
        'Micah' => 'Old Testament--w/o Psalms',
        'Nahum' => 'Old Testament--w/o Psalms',
        'Habakkuk' => 'Old Testament--w/o Psalms',
        'Zephaniah' => 'Old Testament--w/o Psalms',
        'Haggai' => 'Old Testament--w/o Psalms',
        'Zechariah' => 'Old Testament--w/o Psalms',
        'Malachi' => 'Old Testament--w/o Psalms',

        
    ],

    'book_abbrev' => [
        
        'Matthew' => 'Mt',
        'Mark' => 'Mk',
        'Luke' => 'Lk',
        'John' => 'Jn',
        'Acts' => 'Acts',
        'Romans' => 'Rom',
        'Galatians' => 'Gal',
        'Ephesians' => 'Eph',
        'Philippians' => 'Phil',
        'Colossians' => 'Col',
        'Psalm' => 'Ps',
        'Psalms' => 'Ps',
        'Song of Solomon' => 'Sg',
        'The Song of Solomon' => 'Sg',
        // expand as needed

    ],

];